### ISSUE TITLE
关闭某个页面缓存

### ISSUE THREAD

**Issue by ghost** [xyhxx/proste_indexed_stack#1]
请教：如果在底部导航中，page3页面是不需要缓存的，那么如何才能单独关闭这个页面的缓存。
例子：Page1和Page2是保存缓存状态，但page3是购物车或者是收藏页，此时paga3保存缓存状态就无法加载最新添加的数据，需要把page3页面的缓存功能关闭，如何设置。谢谢，希望发个邮件指点一下oouuvs@126.com

ProsteIndexedStack(
        index: _current,
        children: [
             IndexedStackChild(child: Page1()),
             IndexedStackChild(child: Page2()),
             IndexedStackChild(child: Page3()),
       ],
 )

**Comment by xyhxx** [comment]
IndexedStack这个组件本身也是没有缓存这个功能的，他只是展示所有的页面然后根据索引将某一个显示在第一层级上。你的这个需求和这个插件本身是没有关系的，ProsteIndexedStack在切换组件时不会对组件进行销毁操作。

你的这个需求如果你使用了状态管理插件比如Provider或者Getx或者其他的话你是不需要有任何的操作的，你的组件会根据你的数据变化自动更新的。

如果你没有用状态管理插件的话，你可以给page3传入一个GlobalKey，用这个key去执行page3里面的更新数据操作。在你的_current要切换到3之前去用GlobalKey调用对应的page3下的方法就可以了。

或者你把这个GlobalKey提升到全局，每次收藏操作的时候调用对应的page3下的更新方法。
